/*
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */
package br.edu.ifsul.lpoo.assistenciatecnica.gui.usuario;

import br.edu.ifsul.lpoo.assistenciatecnica.Controle;
import br.edu.ifsul.lpoo.assistenciatecnica.model.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Vector;

/**
 *
 * @author telmo
 */
public class JPanelListagem extends javax.swing.JPanel {

            private JPanelUsuario pnlUsuario;
            private Controle controle;

    
            public JPanelListagem(JPanelUsuario pnlUsuario, Controle controle) {
                        this.pnlUsuario = pnlUsuario;
                        this.controle = controle;
                        initComponents();
            }
            
            public void populaTable(){
        
                        DefaultTableModel model =  (DefaultTableModel) tblListagem.getModel();//recuperacao do modelo da tabela

                        model.setRowCount(0);//elimina as linhas existentes (reset na tabela)

                        try {

                            List<Usuario> listUsus = controle.getConexaoJDBC().getUsuarios();
                            for(Usuario u : listUsus){
                                System.out.println("u.getCidade() : "+ u.getCidade() );
                                // vai imprimir apenas o cpf do usuario em função do método toString da classe usuario
                                if(u.getCidade() != null)//como a cidade é opcional, testa antes recuperar a cidade do Usuario
                                    model.addRow(new Object[]{u, u.getNome(), u.getDtultimaacesso(), u.getCidade().getNome()});
                                else
                                    model.addRow(new Object[]{u, u.getNome(), u.getDtultimaacesso(), ""});
                            }

                        } catch (Exception ex) {

                            JOptionPane.showMessageDialog(this, "Erro ao listar Usuarios -:"+ex.getLocalizedMessage(), "Usuários", JOptionPane.ERROR_MESSAGE);
                            ex.printStackTrace();
                        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorte = new javax.swing.JPanel();
        lblPesquisarNome = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        pnlSul = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        scpBarraRolagem = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lblPesquisarNome.setText("Pesquisar por Nome");
        pnlNorte.add(lblPesquisarNome);

        jTextField1.setColumns(10);
        pnlNorte.add(jTextField1);

        btnPesquisar.setText("Pesquisar");
        pnlNorte.add(btnPesquisar);

        add(pnlNorte, java.awt.BorderLayout.PAGE_START);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        pnlSul.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlSul.add(btnEditar);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        pnlSul.add(btnRemover);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Último Acesso", "Cidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpBarraRolagem.setViewportView(tblListagem);

        pnlCentro.add(scpBarraRolagem, java.awt.BorderLayout.CENTER);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        int indice = tblListagem.getSelectedRow();//recupera a linha selecionada
        if(indice > -1){
                      
            DefaultTableModel model =  (DefaultTableModel) tblListagem.getModel(); //recuperacao do modelo da table
                        
            Vector linha = (Vector) model.getDataVector().get(indice);//recupera o vetor de dados da linha selecionada
            
            Usuario u = (Usuario) linha.get(0); //model.addRow(new Object[]{u, u.getNome(), ...
            
            pnlUsuario.showTela("tela_edicao");
            pnlUsuario.getTelaFormulario().populaFormulario(u); 
            
        }else{
              JOptionPane.showMessageDialog(this, "Selecione uma linha para editar!", "Edição", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

            int indice = tblListagem.getSelectedRow();//recupera a linha selecionada
            if(indice > -1){

                DefaultTableModel model =  (DefaultTableModel) tblListagem.getModel(); //recuperacao do modelo da table

                Vector linha = (Vector) model.getDataVector().get(indice);//recupera o vetor de dados da linha selecionada

                Usuario u = (Usuario) linha.get(0); //model.addRow(new Object[]{u, u.getNome(), ...

                try {
                    pnlUsuario.getControle().getConexaoJDBC().remover(u);
                    JOptionPane.showMessageDialog(this, "Usuario removido!", "Usuários", JOptionPane.INFORMATION_MESSAGE);
                    populaTable(); //refresh na tabela

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao remover Usuario -:"+ex.getLocalizedMessage(), "Usuários", JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }                        

            }else{
                  JOptionPane.showMessageDialog(this, "Selecione uma linha para remover!", "Remoção", JOptionPane.INFORMATION_MESSAGE);
            }
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        
                        pnlUsuario.showTela("tela_edicao");
                        pnlUsuario.getTelaFormulario().populaFormulario(null);
        
    }//GEN-LAST:event_btnNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPesquisarNome;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JScrollPane scpBarraRolagem;
    private javax.swing.JTable tblListagem;
    // End of variables declaration//GEN-END:variables
}
